import React from 'react';

const createSimpleTopic = (id, title, theoryText, challengeText, code, validateFn, success) => ({
  id,
  title: `${id}. ${title}`,
  theory: (
    <>
      <h3>{title}</h3>
      <p>{theoryText}</p>
    </>
  ),
  challenge: <p><strong>Challenge:</strong> {challengeText}</p>,
  initialCode: code,
  validate: validateFn,
  successMsg: success
});

export const TOPICS_CONFIG = {
  c: [
    createSimpleTopic(1, "Introduction to C", "C is a powerful general-purpose language.", "Print 'Hello C'", "#include <stdio.h>\nint main() {\n    printf(\"Hello C\");\n    return 0;\n}", (o)=>o.includes('Hello C'), "Success!"),
    createSimpleTopic(2, "Structure of C", "C programs consist of headers and main.", "Print 'Main'", "#include <stdio.h>\nint main() {\n    printf(\"Main\");\n    return 0;\n}", (o)=>o.includes('Main'), "Great!"),
    createSimpleTopic(3, "Tokens in C", "Smallest individual units.", "Print 'Token'", "#include <stdio.h>\nint main() {\n    printf(\"Token\");\n    return 0;\n}", (o)=>o.includes('Token'), "Nice!"),
    createSimpleTopic(4, "Keywords", "Reserved words in C.", "Print 'Keyword'", "#include <stdio.h>\nint main() {\n    printf(\"Keyword\");\n    return 0;\n}", (o)=>o.includes('Keyword'), "Done!"),
    createSimpleTopic(5, "Identifiers", "Names for variables.", "Print 'ID'", "#include <stdio.h>\nint main() {\n    printf(\"ID\");\n    return 0;\n}", (o)=>o.includes('ID'), "Correct!"),
    createSimpleTopic(6, "Variables", "Containers for data.", "Print 'Var'", "#include <stdio.h>\nint main() {\n    printf(\"Var\");\n    return 0;\n}", (o)=>o.includes('Var'), "Var set!"),
    createSimpleTopic(7, "Data Types", "int, float, char.", "Print 'Type'", "#include <stdio.h>\nint main() {\n    printf(\"Type\");\n    return 0;\n}", (o)=>o.includes('Type'), "Typed!"),
    createSimpleTopic(8, "Constants", "Unchangeable values.", "Print 'Const'", "#include <stdio.h>\nint main() {\n    printf(\"Const\");\n    return 0;\n}", (o)=>o.includes('Const'), "Steady!"),
    createSimpleTopic(9, "Operators", "Math and logic.", "Print 'Op'", "#include <stdio.h>\nint main() {\n    printf(\"Op\");\n    return 0;\n}", (o)=>o.includes('Op'), "Computed!"),
    createSimpleTopic(10, "Expressions", "Combinations of tokens.", "Print 'Exp'", "#include <stdio.h>\nint main() {\n    printf(\"Exp\");\n    return 0;\n}", (o)=>o.includes('Exp'), "Evaluated!"),
    createSimpleTopic(11, "Input and Output", "printf and scanf.", "Print 'IO'", "#include <stdio.h>\nint main() {\n    printf(\"IO\");\n    return 0;\n}", (o)=>o.includes('IO'), "Communicated!"),
    createSimpleTopic(12, "Type Casting", "Converting types.", "Print 'Cast'", "#include <stdio.h>\nint main() {\n    printf(\"Cast\");\n    return 0;\n}", (o)=>o.includes('Cast'), "Transformed!"),
    createSimpleTopic(13, "Decision Making", "if and switch.", "Print 'Decision'", "#include <stdio.h>\nint main() {\n    printf(\"Decision\");\n    return 0;\n}", (o)=>o.includes('Decision'), "Decided!"),
    createSimpleTopic(14, "Loops", "for, while, do-while.", "Print '123'", "#include <stdio.h>\nint main() {\n    for(int i=1;i<=3;i++) printf(\"%d\", i);\n    return 0;\n}", (o)=>o.includes('123'), "Repeated!"),
    createSimpleTopic(15, "Break and Continue", "Flow control.", "Print 'Skip'", "#include <stdio.h>\nint main() {\n    printf(\"Skip\");\n    return 0;\n}", (o)=>o.includes('Skip'), "Controlled!"),
    createSimpleTopic(16, "Arrays", "Contiguous data.", "Print 'Arr'", "#include <stdio.h>\nint main() {\n    printf(\"Arr\");\n    return 0;\n}", (o)=>o.includes('Arr'), "Indexed!"),
    createSimpleTopic(17, "Strings", "Character arrays.", "Print 'Str'", "#include <stdio.h>\nint main() {\n    printf(\"Str\");\n    return 0;\n}", (o)=>o.includes('Str'), "Textual!"),
    createSimpleTopic(18, "Functions", "Modular code.", "Print 'Func'", "#include <stdio.h>\nint main() {\n    printf(\"Func\");\n    return 0;\n}", (o)=>o.includes('Func'), "Reusable!"),
    createSimpleTopic(19, "Recursion", "Self-calling functions.", "Print 'Rec'", "#include <stdio.h>\nint main() {\n    printf(\"Rec\");\n    return 0;\n}", (o)=>o.includes('Rec'), "Deeper!"),
    createSimpleTopic(20, "Storage Classes", "Scope and lifetime.", "Print 'Store'", "#include <stdio.h>\nint main() {\n    printf(\"Store\");\n    return 0;\n}", (o)=>o.includes('Store'), "Scoped!"),
    createSimpleTopic(21, "Pointers", "Memory addresses.", "Print 'Ptr'", "#include <stdio.h>\nint main() {\n    printf(\"Ptr\");\n    return 0;\n}", (o)=>o.includes('Ptr'), "Pointed!"),
    createSimpleTopic(22, "Pointer Arithmetic", "Moving in memory.", "Print 'Add'", "#include <stdio.h>\nint main() {\n    printf(\"Add\");\n    return 0;\n}", (o)=>o.includes('Add'), "Offset!"),
    createSimpleTopic(23, "Pointers and Arrays", "Hidden connection.", "Print 'Connect'", "#include <stdio.h>\nint main() {\n    printf(\"Connect\");\n    return 0;\n}", (o)=>o.includes('Connect'), "Unified!"),
    createSimpleTopic(24, "Pointers and Functions", "Pass by reference.", "Print 'Ref'", "#include <stdio.h>\nint main() {\n    printf(\"Ref\");\n    return 0;\n}", (o)=>o.includes('Ref'), "Modified!"),
    createSimpleTopic(25, "Structures", "Grouping data.", "Print 'Struct'", "#include <stdio.h>\nint main() {\n    printf(\"Struct\");\n    return 0;\n}", (o)=>o.includes('Struct'), "Grouped!"),
    createSimpleTopic(26, "Unions", "Shared memory.", "Print 'Union'", "#include <stdio.h>\nint main() {\n    printf(\"Union\");\n    return 0;\n}", (o)=>o.includes('Union'), "Overlayed!"),
    createSimpleTopic(27, "Enumerations", "Named constants.", "Print 'Enum'", "#include <stdio.h>\nint main() {\n    printf(\"Enum\");\n    return 0;\n}", (o)=>o.includes('Enum'), "Named!"),
    createSimpleTopic(28, "Dynamic Memory", "Heap allocation.", "Print 'Malloc'", "#include <stdio.h>\nint main() {\n    printf(\"Malloc\");\n    return 0;\n}", (o)=>o.includes('Malloc'), "Allocated!"),
    createSimpleTopic(29, "File Handling", "fopen and fclose.", "Print 'File'", "#include <stdio.h>\nint main() {\n    printf(\"File\");\n    return 0;\n}", (o)=>o.includes('File'), "Stored!"),
    createSimpleTopic(30, "CMD Arguments", "argc and argv.", "Print 'Args'", "#include <stdio.h>\nint main() {\n    printf(\"Args\");\n    return 0;\n}", (o)=>o.includes('Args'), "Interfaced!"),
    createSimpleTopic(31, "Preprocessor", "Before compilation.", "Print 'Pre'", "#include <stdio.h>\nint main() {\n    printf(\"Pre\");\n    return 0;\n}", (o)=>o.includes('Pre'), "Processed!"),
    createSimpleTopic(32, "Header Files", ".h files.", "Print 'Header'", "#include <stdio.h>\nint main() {\n    printf(\"Header\");\n    return 0;\n}", (o)=>o.includes('Header'), "Included!"),
    createSimpleTopic(33, "Bitwise", "Bit-level ops.", "Print 'Bit'", "#include <stdio.h>\nint main() {\n    printf(\"Bit\");\n    return 0;\n}", (o)=>o.includes('Bit'), "Binary!"),
    createSimpleTopic(34, "Error Handling", "errno and strerror.", "Print 'Err'", "#include <stdio.h>\nint main() {\n    printf(\"Err\");\n    return 0;\n}", (o)=>o.includes('Err'), "Caught!"),
    createSimpleTopic(35, "Macros", "C code templates.", "Print 'Macro'", "#include <stdio.h>\nint main() {\n    printf(\"Macro\");\n    return 0;\n}", (o)=>o.includes('Macro'), "Expanded!")
  ],
  python: [
    createSimpleTopic(1, "Introduction to Python", "Python is simple and high-level.", "Print 'Hello Python'", "print('Hello Python')", (o)=>o.includes('Hello Python'), "Welcome!"),
    createSimpleTopic(2, "Python Installation", "Setting up local env.", "Print 'Live'", "print('Live')", (o)=>o.includes('Live'), "Active!"),
    createSimpleTopic(3, "Variables and Data Types", "Dynamic typing.", "Print '42'", "x=42\nprint(x)", (o)=>o.trim()==='42', "Typed!"),
    createSimpleTopic(4, "Input and Output", "print() function.", "Print 'Ready'", "print('Ready')", (o)=>o.includes('Ready'), "Ready!"),
    createSimpleTopic(5, "Operators", "Math and logic.", "Print 5*5", "print(5*5)", (o)=>o.trim()==='25', "Computed!"),
    createSimpleTopic(6, "Conditional Statements", "if/elif/else.", "Print 'Yes' if True", "if True: print('Yes')", (o)=>o.includes('Yes'), "Branching!"),
    createSimpleTopic(7, "Loops", "for and while.", "Print 123", "for i in [1,2,3]: print(i, end='')", (o)=>o.trim()==='123', "Repeating!"),
    createSimpleTopic(8, "Functions", "def keyword.", "Print 'Func'", "def f(): print('Func')\nf()", (o)=>o.includes('Func'), "Modular!"),
    createSimpleTopic(9, "Lambda Functions", "One-liners.", "Print 'Lambda'", "f=lambda:print('Lambda')\nf()", (o)=>o.includes('Lambda'), "Swift!"),
    createSimpleTopic(10, "Lists", "Mutable sequences.", "Print [1,2]", "print([1,2])", (o)=>o.includes('[1, 2]'), "Collected!"),
    createSimpleTopic(11, "Tuples", "Immutable sequences.", "Print (1,2)", "print((1,2))", (o)=>o.includes('(1, 2)'), "Safe!"),
    createSimpleTopic(12, "Sets", "Unique elements.", "Print {1}", "print({1})", (o)=>o.includes('{1}'), "Unique!"),
    createSimpleTopic(13, "Dictionaries", "Key-value pairs.", "Print {'k':1}", "print({'k':1})", (o)=>o.includes("'k': 1"), "Mapped!"),
    createSimpleTopic(14, "Strings", "Character sequences.", "Print 'Python'", "print('Python')", (o)=>o.includes('Python'), "Literal!"),
    createSimpleTopic(15, "List Comprehension", "Inline list creation.", "Square 1 to 2", "print([x*x for x in [1,2]])", (o)=>o.includes('[1, 4]'), "Elegant!"),
    createSimpleTopic(16, "Modules and Packages", "import syntax.", "Print 'Math'", "print('Math')", (o)=>o.includes('Math'), "Included!"),
    createSimpleTopic(17, "Exception Handling", "try-except.", "Print 'Error'", "try: 1/0\nexcept: print('Error')", (o)=>o.includes('Error'), "Resilient!"),
    createSimpleTopic(18, "File Handling", "with open().", "Print 'File'", "print('File')", (o)=>o.includes('File'), "Stored!"),
    createSimpleTopic(19, "OOP", "Object principles.", "Print 'OOP'", "print('OOP')", (o)=>o.includes('OOP'), "Principled!"),
    createSimpleTopic(20, "Classes and Objects", "Blueprints.", "Print 'Class'", "print('Class')", (o)=>o.includes('Class'), "Blueprinted!"),
    createSimpleTopic(21, "Inheritance", "Child classes.", "Print 'Inherit'", "print('Inherit')", (o)=>o.includes('Inherit'), "Derived!"),
    createSimpleTopic(22, "Polymorphism", "Common methods.", "Print 'Poly'", "print('Poly')", (o)=>o.includes('Poly'), "Versatile!"),
    createSimpleTopic(23, "Encapsulation", "_private members.", "Print 'Private'", "print('Private')", (o)=>o.includes('Private'), "Secret!"),
    createSimpleTopic(24, "Iterators and Generators", "yield keyword.", "Print 'Yield'", "print('Yield')", (o)=>o.includes('Yield'), "Flowing!"),
    createSimpleTopic(25, "Decorators", "Wrappers.", "Print 'Wrapped'", "print('Wrapped')", (o)=>o.includes('Wrapped'), "Enhanced!"),
    createSimpleTopic(26, "Regular Expressions", "re module.", "Print 'Match'", "print('Match')", (o)=>o.includes('Match'), "Found!"),
    createSimpleTopic(27, "Multithreading", "threading.", "Print 'Thread'", "print('Thread')", (o)=>o.includes('Thread'), "Parallel!"),
    createSimpleTopic(28, "Database", "sqlite3.", "Print 'DB'", "print('DB')", (o)=>o.includes('DB'), "Connected!"),
    createSimpleTopic(29, "GUI Programming", "Tkinter.", "Print 'GUI'", "print('GUI')", (o)=>o.includes('GUI'), "Windowed!"),
    createSimpleTopic(30, "Virtual Environment", "venv usage.", "Print 'Clean'", "print('Clean')", (o)=>o.includes('Clean'), "Isolated!")
  ],
  java: [
    createSimpleTopic(1, "Introduction to Java", "Object-oriented and robust.", "Print 'Java'", "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Java\");\n    }\n}", (o)=>o.includes('Java'), "Welcome!"),
    createSimpleTopic(2, "JVM, JRE, JDK", "The Java architecture.", "Print 'JVM'", "public class Main { public static void main(String[] args){ System.out.println(\"JVM\"); } }", (o)=>o.includes('JVM'), "Internalized!"),
    createSimpleTopic(3, "Program Structure", "Classes and methods.", "Print 'Main'", "public class Main { public static void main(String[] args){ System.out.println(\"Main\"); } }", (o)=>o.includes('Main'), "Structured!"),
    createSimpleTopic(4, "Variables", "Strongly typed.", "Print '10'", "public class Main { public static void main(String[] args){ int x=10; System.out.println(x); } }", (o)=>o.trim()==='10', "Typed!"),
    createSimpleTopic(5, "Operators", "Math and logic.", "Print 1+1", "public class Main { public static void main(String[] args){ System.out.println(1+1); } }", (o)=>o.trim()==='2', "Computed!"),
    createSimpleTopic(6, "Type Casting", "Widening/Narrowing.", "Print '3'", "public class Main { public static void main(String[] args){ System.out.println((int)3.5); } }", (o)=>o.trim()==='3', "Converted!"),
    createSimpleTopic(7, "Conditionals", "if/switch.", "Print 'Yes'", "public class Main { public static void main(String[] args){ if(true) System.out.println(\"Yes\"); } }", (o)=>o.includes('Yes'), "Branching!"),
    createSimpleTopic(8, "Loops", "for/while.", "Print '111'", "public class Main { public static void main(String[] args){ for(int i=0;i<3;i++) System.out.print(1); } }", (o)=>o.trim()==='111', "Repeated!"),
    createSimpleTopic(9, "Arrays", "Fixed-size storage.", "Print 7", "public class Main { public static void main(String[] args){ int[] a={7}; System.out.println(a[0]); } }", (o)=>o.trim()==='7', "Indexed!"),
    createSimpleTopic(10, "Strings", "java.lang.String.", "Print 'Str'", "public class Main { public static void main(String[] args){ System.out.println(\"Str\"); } }", (o)=>o.includes('Str'), "Literal!"),
    createSimpleTopic(11, "Methods", "Functions in classes.", "Print 'Hi'", "public class Main { static void hi(){System.out.println(\"Hi\");} public static void main(String[] args){hi();} }", (o)=>o.includes('Hi'), "Modular!"),
    createSimpleTopic(12, "Constructors", "Object init.", "Print 'Init'", "public class Main { public static void main(String[] args){ System.out.println(\"Init\"); } }", (o)=>o.includes('Init'), "Born!"),
    createSimpleTopic(13, "OOP", "Inheritance, Encapsulation.", "Print 'OOP'", "public class Main { public static void main(String[] args){ System.out.println(\"OOP\"); } }", (o)=>o.includes('OOP'), "Principled!"),
    createSimpleTopic(14, "Classes and Objects", "Instances.", "Print 'Obj'", "public class Main { public static void main(String[] args){ System.out.println(\"Obj\"); } }", (o)=>o.includes('Obj'), "Realized!"),
    createSimpleTopic(15, "Inheritance", "Parent/Child.", "Print 'Parent'", "public class Main { public static void main(String[] args){ System.out.println(\"Parent\"); } }", (o)=>o.includes('Parent'), "Legacy!"),
    createSimpleTopic(16, "Polymorphism", "Many forms.", "Print 'Poly'", "public class Main { public static void main(String[] args){ System.out.println(\"Poly\"); } }", (o)=>o.includes('Poly'), "Versatile!"),
    createSimpleTopic(17, "Abstraction", "Interface/Abstract.", "Print 'Hide'", "public class Main { public static void main(String[] args){ System.out.println(\"Hide\"); } }", (o)=>o.includes('Hide'), "Abstract!"),
    createSimpleTopic(18, "Encapsulation", "Safe members.", "Print 'Safe'", "public class Main { public static void main(String[] args){ System.out.println(\"Safe\"); } }", (o)=>o.includes('Safe'), "Secured!"),
    createSimpleTopic(19, "Packages", "Groupings.", "Print 'Pkg'", "public class Main { public static void main(String[] args){ System.out.println(\"Pkg\"); } }", (o)=>o.includes('Pkg'), "Organized!"),
    createSimpleTopic(20, "Access Modifiers", "public/private.", "Print 'Access'", "public class Main { public static void main(String[] args){ System.out.println(\"Access\"); } }", (o)=>o.includes('Access'), "Permitted!"),
    createSimpleTopic(21, "Exception Handling", "Errors.", "Print 'Err'", "public class Main { public static void main(String[] args){ System.out.println(\"Err\"); } }", (o)=>o.includes('Err'), "Handled!"),
    createSimpleTopic(22, "Multithreading", "Parallel.", "Print 'Thread'", "public class Main { public static void main(String[] args){ System.out.println(\"Thread\"); } }", (o)=>o.includes('Thread'), "Simultaneous!"),
    createSimpleTopic(23, "File Handling", "File IO.", "Print 'File'", "public class Main { public static void main(String[] args){ System.out.println(\"File\"); } }", (o)=>o.includes('File'), "Stored!"),
    createSimpleTopic(24, "Collections", "ArrayList/Map.", "Print 'Coll'", "public class Main { public static void main(String[] args){ System.out.println(\"Coll\"); } }", (o)=>o.includes('Coll'), "Grouped!"),
    createSimpleTopic(25, "Interfaces", "Contracts.", "Print 'Base'", "public class Main { public static void main(String[] args){ System.out.println(\"Base\"); } }", (o)=>o.includes('Base'), "Contracted!"),
    createSimpleTopic(26, "Abstract Classes", "Foundation.", "Print 'Found'", "public class Main { public static void main(String[] args){ System.out.println(\"Found\"); } }", (o)=>o.includes('Found'), "Base!"),
    createSimpleTopic(27, "JDBC", "SQL Access.", "Print 'JDBC'", "public class Main { public static void main(String[] args){ System.out.println(\"JDBC\"); } }", (o)=>o.includes('JDBC'), "Informed!"),
    createSimpleTopic(28, "GUI", "Swing.", "Print 'GUI'", "public class Main { public static void main(String[] args){ System.out.println(\"GUI\"); } }", (o)=>o.includes('GUI'), "Visual!"),
    createSimpleTopic(29, "Lambda", "Functional Java.", "Print 'Lambda'", "public class Main { public static void main(String[] args){ System.out.println(\"Lambda\"); } }", (o)=>o.includes('Lambda'), "Modern!"),
    createSimpleTopic(30, "Stream API", "Processing data.", "Print 'Stream'", "public class Main { public static void main(String[] args){ System.out.println(\"Stream\"); } }", (o)=>o.includes('Stream'), "Fluent!")
  ],
  cpp: [
    createSimpleTopic(1, "Introduction to C++", "High-level extension of C.", "Print 'CPP'", "#include <iostream>\nint main() { std::cout << \"CPP\"; return 0; }", (o)=>o.includes('CPP'), "Welcome!"),
    createSimpleTopic(2, "Structure", "main and headers.", "Print 'Main'", "#include <iostream>\nint main() { std::cout << \"Main\"; return 0; }", (o)=>o.includes('Main'), "Structured!"),
    createSimpleTopic(3, "Variables", "Typed containers.", "Print '10'", "#include <iostream>\nint main() { int x=10; std::cout << x; return 0; }", (o)=>o.trim()==='10', "Typed!"),
    createSimpleTopic(4, "Operators", "Math/Bitwise.", "Print '5'", "#include <iostream>\nint main() { std::cout << 5; return 0; }", (o)=>o.trim()==='5', "Computed!"),
    createSimpleTopic(5, "Input and Output", "cin/cout.", "Print 'IO'", "#include <iostream>\nint main() { std::cout << \"IO\"; return 0; }", (o)=>o.includes('IO'), "Ready!"),
    createSimpleTopic(6, "Conditionals", "if/else.", "Print 'Yes'", "#include <iostream>\nint main() { std::cout << \"Yes\"; return 0; }", (o)=>o.includes('Yes'), "Branching!"),
    createSimpleTopic(7, "Loops", "for/while.", "Print '123'", "#include <iostream>\nint main() { for(int i=1;i<4;i++) std::cout << i; return 0; }", (o)=>o.trim()==='123', "Repeating!"),
    createSimpleTopic(8, "Functions", "Reusability.", "Print 'F'", "#include <iostream>\nvoid f(){std::cout<<\"F\";}\nint main() { f(); return 0; }", (o)=>o.includes('F'), "Modular!"),
    createSimpleTopic(9, "Function Overloading", "Multi-signature.", "Print 'Over'", "#include <iostream>\nint main() { std::cout << \"Over\"; return 0; }", (o)=>o.includes('Over'), "Flexible!"),
    createSimpleTopic(10, "Classes and Objects", "Encapsulation.", "Print 'Obj'", "#include <iostream>\nint main() { std::cout << \"Obj\"; return 0; }", (o)=>o.includes('Obj'), "Principled!"),
    createSimpleTopic(11, "Constructors", "Init logic.", "Print 'Init'", "#include <iostream>\nint main() { std::cout << \"Init\"; return 0; }", (o)=>o.includes('Init'), "Starting!"),
    createSimpleTopic(12, "Encapsulation", "Access control.", "Print 'Safe'", "#include <iostream>\nint main() { std::cout << \"Safe\"; return 0; }", (o)=>o.includes('Safe'), "Secured!"),
    createSimpleTopic(13, "Inheritance", "Derivation.", "Print 'Base'", "#include <iostream>\nint main() { std::cout << \"Base\"; return 0; }", (o)=>o.includes('Base'), "Extended!"),
    createSimpleTopic(14, "Polymorphism", "Virtual behavior.", "Print 'Poly'", "#include <iostream>\nint main() { std::cout << \"Poly\"; return 0; }", (o)=>o.includes('Poly'), "Versatile!"),
    createSimpleTopic(15, "Abstraction", "Interface.", "Print 'Abs'", "#include <iostream>\nint main() { std::cout << \"Abs\"; return 0; }", (o)=>o.includes('Abs'), "Generic!"),
    createSimpleTopic(16, "Friend Functions", "Private access.", "Print 'Friend'", "#include <iostream>\nint main() { std::cout << \"Friend\"; return 0; }", (o)=>o.includes('Friend'), "Trusted!"),
    createSimpleTopic(17, "Operator Overloading", "Custom ops.", "Print 'Plus'", "#include <iostream>\nint main() { std::cout << \"Plus\"; return 0; }", (o)=>o.includes('Plus'), "Custom!"),
    createSimpleTopic(18, "Pointers", "Addresses.", "Print 'Addr'", "#include <iostream>\nint main() { std::cout << \"Addr\"; return 0; }", (o)=>o.includes('Addr'), "Pointing!"),
    createSimpleTopic(19, "References", "Aliases.", "Print 'Alias'", "#include <iostream>\nint main() { std::cout << \"Alias\"; return 0; }", (o)=>o.includes('Alias'), "Aliased!"),
    createSimpleTopic(20, "Arrays", "Contiguous.", "Print '99'", "#include <iostream>\nint main() { int a[]={99}; std::cout << a[0]; return 0; }", (o)=>o.trim()==='99', "Indexed!"),
    createSimpleTopic(21, "Strings", "std::string.", "Print 'String'", "#include <iostream>\n#include <string>\nint main() { std::string s=\"String\"; std::cout << s; return 0; }", (o)=>o.includes('String'), "Textual!"),
    createSimpleTopic(22, "File Handling", "fstream.", "Print 'File'", "#include <iostream>\nint main() { std::cout << \"File\"; return 0; }", (o)=>o.includes('File'), "Stored!"),
    createSimpleTopic(23, "Exception Handling", "try/catch.", "Print 'Err'", "#include <iostream>\nint main() { std::cout << \"Err\"; return 0; }", (o)=>o.includes('Err'), "Resilient!"),
    createSimpleTopic(24, "Templates", "Generics.", "Print 'Template'", "#include <iostream>\nint main() { std::cout << \"Template\"; return 0; }", (o)=>o.includes('Template'), "Generic!"),
    createSimpleTopic(25, "STL", "Standard Library.", "Print 'STL'", "#include <iostream>\nint main() { std::cout << \"STL\"; return 0; }", (o)=>o.includes('STL'), "Standard!"),
    createSimpleTopic(26, "Vectors", "Dynamic arr.", "Print '55'", "#include <iostream>\n#include <vector>\nint main() { std::vector<int> v={55}; std::cout << v[0]; return 0; }", (o)=>o.trim()==='55', "Dynamic!"),
    createSimpleTopic(27, "Lists", "Linked lists.", "Print 'List'", "#include <iostream>\nint main() { std::cout << \"List\"; return 0; }", (o)=>o.includes('List'), "Linked!"),
    createSimpleTopic(28, "Maps", "K-V pairs.", "Print '1'", "#include <iostream>\n#include <map>\nint main() { std::map<char,int> m; m['a']=1; std::cout << m['a']; return 0; }", (o)=>o.trim()==='1', "Mapped!"),
    createSimpleTopic(29, "Iterators", "Navigation.", "Print 'Iter'", "#include <iostream>\nint main() { std::cout << \"Iter\"; return 0; }", (o)=>o.includes('Iter'), "Navigated!"),
    createSimpleTopic(30, "Namespaces", "Scoping.", "Print 'Space'", "#include <iostream>\nint main() { std::cout << \"Space\"; return 0; }", (o)=>o.includes('Space'), "Scoped!")
  ]
};

export const TOPICS = TOPICS_CONFIG.c;
